### ISSUE TITLE
Examples do not appear to be working

### ISSUE THREAD

**Issue by mores** [jetty-project/embedded-servlet-server#178]
I have tried both 10.x and 11.x - they are not working for me.

Console output:
![image](https://github.com/jetty-project/embedded-servlet-server/assets/1318377/e02d71dc-cc52-44cd-8b0b-f8aeb45c9978)

Root of the webapp:
![image](https://github.com/jetty-project/embedded-servlet-server/assets/1318377/a7135d7f-1a8c-4b9f-94f8-4ee5d023ed88)

When I click on html:
![image](https://github.com/jetty-project/embedded-servlet-server/assets/1318377/5b3fc03b-9eae-4af8-bbb8-6a98fda84332)

Time servlet:
![image](https://github.com/jetty-project/embedded-servlet-server/assets/1318377/d020327d-8204-4fd8-a0a1-b07c9e0a5c6c)

**Comment by joakime** [comment]
Please detail how you started your server (command line, OS, java version, maven version)

I used `mvn clean install exec:exec` and then loaded the website from `http://localhost:8080/`

![embedded-servlet-server](https://github.com/jetty-project/embedded-servlet-server/assets/191721/c726380c-2b0f-444d-9f40-c3ea58883884)

**Comment by mores** [comment]
per README.md

mvn clean **compile** exec:exec

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

$ java -version
openjdk version "11.0.17" 2022-10-18 LTS
OpenJDK Runtime Environment Zulu11.60+19-CA (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)


$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/smore/apache-maven-3.6.3
Java version: 11.0.17, vendor: Azul Systems, Inc., runtime: /usr/lib/jvm/zulu-11-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-1039-azure", arch: "amd64", family: "unix"


After issuing: `mvn clean install exec:exec` it works as expected.

Looks like the README needs to be updated.

**Comment by joakime** [comment]
> $ mvn -version Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f) 
> Maven home: /home/smore/apache-maven-3.6.3 

This is also a point that has caused problems for others.
Maven 3.6.x has some incompatibilities with the newer Maven Plugins this project is using.
It is built / tested on Maven 3.9.x.

> After issuing: `mvn clean install exec:exec` it works as expected.
> 
> Looks like the README needs to be updated.

Done, README updated. - a96438125dda5ba9f6ea793e7f967f87a36450f3
