### ISSUE TITLE
The use of @ webservlet in the example does not take effect

### ISSUE THREAD

**Issue by youngledo** [jetty-project/embedded-servlet-server#51]
HTTP ERROR 404 Not Found
URI:	/time
STATUS:	404
MESSAGE:	Not Found
SERVLET:	default
Powered by Jetty:// 10.0.8

**Comment by janbartel** [comment]
You will have to provide more information. I followed the instructions in the README and ran as indicated, and the app works fine on all urls.

**Comment by youngledo** [comment]
I downloaded this demo without making any changes and started it.
I hope to visit http://localhost:8080/time , but 404 is returned
<img width="1144" alt="企业微信20220217-175750@2x" src="https://user-images.githubusercontent.com/68590897/154451666-161e26a3-89b2-4597-b8e8-75d3e9c53b87.png">

<img width="608" alt="企业微信20220217-180616@2x" src="https://user-images.githubusercontent.com/68590897/154453265-20fee74d-374f-40dc-82c2-fe39be00426d.png">

**Comment by joakime** [comment]
Looks like you are using the `jetty-10.0.x` branch here.

What version of Java and Maven are you using?  (just run `mvn --version` and report the output, it includes the JVM details)

**Comment by janbartel** [comment]
@youngledo there are a couple of bugs in the code, but the workaround is to run `mvn clean install exec:exec`.  Note that it is `install`, not `compile`. 

The bugs are both related to execution after only the `compile` phase:

1.  the resource base is determined to be `src/main/webapp/WEB-INF/` instead of `src/main/java/webapp`
2.  the servlet classes are on the server's classpath rather than in `WEB-INF/classes`, and by default we do not scan any classes in the server's classpath for annotations

@joakime I think the easiest thing to do here is to simply change the instructions to reference the `install` phase.

**Comment by joakime** [comment]
@janbartel yes, i agree.

I have a few more changes incoming too ... updated plugin versions, and including a test case.

**Comment by janbartel** [comment]
@joakime if you want to fix it so it works with both unassembled and assembled wars, ie `compile` and `install` phases, do something like this in the `findWebResourceBase` method:

```
            // Try the source path next
            Path srcWebapp = pwd.resolve("src/main/webapp/" + webResourceRef);
            if (Files.exists(srcWebapp))
            {
                uri = srcWebapp.getParent().getParent().toUri();
                System.err.printf("WebResourceBase (Using /src/main/webapp/ Path) %s%n", uri);
                context.setBaseResource(Resource.newResource(uri));
                //ensure just classes from the webapp that are on the server classpath are scanned for annotations
                context.setAttribute("org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern",".*/target/classes/.*$");
                //this package is normally hidden from the webapp, so expose it
                context.getServerClassMatcher().add("-org.eclipse.jetty.demos.");
                return;
            }
```

**Comment by youngledo** [comment]
> Looks like you are using the `jetty-10.0.x` branch here.
> 
> What version of Java and Maven are you using? (just run `mvn --version` and report the output, it includes the JVM details)

Not just the `jetty-10.0.x`  branch, but I use the `jetty-11.0.x`  branch as well.

**Comment by apetrichkovich** [comment]
Hello.
jetty-10.0.13; jvm 11.0.16+8-LTS

Will it be fixed?

**Comment by youngledo** [comment]
> Hello. jetty-10.0.13; jvm 11.0.16+8-LTS
> 
> Will it be fixed?

In fact, the repair code has been given above, but the code in the project(embedded-servlet-server) has not been adjusted.

https://github.com/jetty-project/embedded-servlet-server/issues/51#issuecomment-1044231595
